# The majority of the Supplejack API code is Crown copyright (C) 2014, New Zealand Government, 
# and is licensed under the GNU General Public License, version 3.
# One component is a third party component. See https://github.com/DigitalNZ/supplejack_api for details. 
# 
# Supplejack was created by DigitalNZ at the National Library of NZ and 
# the Department of Internal Affairs. http://digitalnz.org/supplejack

development:
  solr:
    hostname: localhost
    port: 8982
    path: /solr
    log_level: INFO

test:
  solr:
    hostname: solr
    port: 8983
    path: /solr
    log_level: DEBUG
    solr_home: solr

# production:
#   solr:
#     hostname: localhost
#     port: 8983
#     log_level: WARNING
#     # read_timeout: 2solr
#     # open_timeout: 0.5

# staging:
#   solr:
#     hostname: localhost
#     port: 8080
#     path: '/solr4'
#     log_level: WARNING 
#     pid_dir: '/var/run/tomcat'
#     auto_commit_after_request: false
